package hibernate;
// Generated 18/09/2023 13:15:55 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * MslfVendedor generated by hbm2java
 */
@Entity
@Table(name="MSLF_Vendedor"
    ,catalog="db_mateus_fonseca"
)
public class MslfVendedor  implements java.io.Serializable {


     private int mslfIdVendedor;
     private MslfUsuarios mslfUsuarios;
     private String mslfNome;
     private String mslfEmail;
     private String mslfCpf;
     private String mslfRg;
     private String mslfSexo;
     private String mslfTelefone;
     private Date mslfDataNasc;
     private String mslfSalario;

    public MslfVendedor() {
    }

	
    public MslfVendedor(int mslfIdVendedor, MslfUsuarios mslfUsuarios, String mslfNome, String mslfEmail, String mslfCpf, String mslfRg, String mslfSexo, String mslfTelefone, Date mslfDataNasc, String mslfSalario) {
        this.mslfIdVendedor = mslfIdVendedor;
        this.mslfUsuarios = mslfUsuarios;
        this.mslfNome = mslfNome;
        this.mslfEmail = mslfEmail;
        this.mslfCpf = mslfCpf;
        this.mslfRg = mslfRg;
        this.mslfSexo = mslfSexo;
        this.mslfTelefone = mslfTelefone;
        this.mslfDataNasc = mslfDataNasc;
        this.mslfSalario = mslfSalario;
    }
    
   
     @Id 

    
    @Column(name="MSLF_idVendedor", unique=true, nullable=false)
    public int getMslfIdVendedor() {
        return this.mslfIdVendedor;
    }
    
    public void setMslfIdVendedor(int mslfIdVendedor) {
        this.mslfIdVendedor = mslfIdVendedor;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="MSLF_idUsuarios", nullable=false)
    public MslfUsuarios getMslfUsuarios() {
        return this.mslfUsuarios;
    }
    
    public void setMslfUsuarios(MslfUsuarios mslfUsuarios) {
        this.mslfUsuarios = mslfUsuarios;
    }

    
    @Column(name="MSLF_nome", nullable=false, length=100)
    public String getMslfNome() {
        return this.mslfNome;
    }
    
    public void setMslfNome(String mslfNome) {
        this.mslfNome = mslfNome;
    }

    
    @Column(name="MSLF_email", nullable=false, length=100)
    public String getMslfEmail() {
        return this.mslfEmail;
    }
    
    public void setMslfEmail(String mslfEmail) {
        this.mslfEmail = mslfEmail;
    }

    
    @Column(name="MSLF_cpf", nullable=false, length=30)
    public String getMslfCpf() {
        return this.mslfCpf;
    }
    
    public void setMslfCpf(String mslfCpf) {
        this.mslfCpf = mslfCpf;
    }

    
    @Column(name="MSLF_rg", nullable=false, length=30)
    public String getMslfRg() {
        return this.mslfRg;
    }
    
    public void setMslfRg(String mslfRg) {
        this.mslfRg = mslfRg;
    }

    
    @Column(name="MSLF_sexo", nullable=false, length=10)
    public String getMslfSexo() {
        return this.mslfSexo;
    }
    
    public void setMslfSexo(String mslfSexo) {
        this.mslfSexo = mslfSexo;
    }

    
    @Column(name="MSLF_telefone", nullable=false, length=45)
    public String getMslfTelefone() {
        return this.mslfTelefone;
    }
    
    public void setMslfTelefone(String mslfTelefone) {
        this.mslfTelefone = mslfTelefone;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="MSLF_data_nasc", nullable=false, length=10)
    public Date getMslfDataNasc() {
        return this.mslfDataNasc;
    }
    
    public void setMslfDataNasc(Date mslfDataNasc) {
        this.mslfDataNasc = mslfDataNasc;
    }

    
    @Column(name="MSLF_salario", nullable=false, length=45)
    public String getMslfSalario() {
        return this.mslfSalario;
    }
    
    public void setMslfSalario(String mslfSalario) {
        this.mslfSalario = mslfSalario;
    }



}


