package hibernate;
// Generated 18/09/2023 13:15:55 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * MslfCliente generated by hbm2java
 */
@Entity
@Table(name="MSLF_Cliente"
    ,catalog="db_mateus_fonseca"
)
public class MslfCliente  implements java.io.Serializable {


     private int mslfIdCliente;
     private MslfUsuarios mslfUsuarios;
     private String mslfNome;
     private String mslfApelido;
     private String mslfEmail;
     private String mslfCpf;
     private String mslfRg;
     private String mslfSexo;
     private String mslfTelefone;
     private Date mslfSenha;
     private String mslfCep;
     private String mslfEndereco;
     private String mslfBairro;
     private String mslfCidade;
     private String mslfEstado;

    public MslfCliente() {
    }

	
    public MslfCliente(int mslfIdCliente, MslfUsuarios mslfUsuarios, String mslfNome, String mslfEmail, String mslfCpf, String mslfRg, String mslfSexo, String mslfTelefone, Date mslfSenha, String mslfCep, String mslfEndereco, String mslfBairro, String mslfCidade, String mslfEstado) {
        this.mslfIdCliente = mslfIdCliente;
        this.mslfUsuarios = mslfUsuarios;
        this.mslfNome = mslfNome;
        this.mslfEmail = mslfEmail;
        this.mslfCpf = mslfCpf;
        this.mslfRg = mslfRg;
        this.mslfSexo = mslfSexo;
        this.mslfTelefone = mslfTelefone;
        this.mslfSenha = mslfSenha;
        this.mslfCep = mslfCep;
        this.mslfEndereco = mslfEndereco;
        this.mslfBairro = mslfBairro;
        this.mslfCidade = mslfCidade;
        this.mslfEstado = mslfEstado;
    }
    public MslfCliente(int mslfIdCliente, MslfUsuarios mslfUsuarios, String mslfNome, String mslfApelido, String mslfEmail, String mslfCpf, String mslfRg, String mslfSexo, String mslfTelefone, Date mslfSenha, String mslfCep, String mslfEndereco, String mslfBairro, String mslfCidade, String mslfEstado) {
       this.mslfIdCliente = mslfIdCliente;
       this.mslfUsuarios = mslfUsuarios;
       this.mslfNome = mslfNome;
       this.mslfApelido = mslfApelido;
       this.mslfEmail = mslfEmail;
       this.mslfCpf = mslfCpf;
       this.mslfRg = mslfRg;
       this.mslfSexo = mslfSexo;
       this.mslfTelefone = mslfTelefone;
       this.mslfSenha = mslfSenha;
       this.mslfCep = mslfCep;
       this.mslfEndereco = mslfEndereco;
       this.mslfBairro = mslfBairro;
       this.mslfCidade = mslfCidade;
       this.mslfEstado = mslfEstado;
    }
   
     @Id 

    
    @Column(name="MSLF_idCliente", unique=true, nullable=false)
    public int getMslfIdCliente() {
        return this.mslfIdCliente;
    }
    
    public void setMslfIdCliente(int mslfIdCliente) {
        this.mslfIdCliente = mslfIdCliente;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="MSLF_idUsuarios", nullable=false)
    public MslfUsuarios getMslfUsuarios() {
        return this.mslfUsuarios;
    }
    
    public void setMslfUsuarios(MslfUsuarios mslfUsuarios) {
        this.mslfUsuarios = mslfUsuarios;
    }

    
    @Column(name="MSLF_nome", nullable=false, length=100)
    public String getMslfNome() {
        return this.mslfNome;
    }
    
    public void setMslfNome(String mslfNome) {
        this.mslfNome = mslfNome;
    }

    
    @Column(name="MSLF_apelido", length=45)
    public String getMslfApelido() {
        return this.mslfApelido;
    }
    
    public void setMslfApelido(String mslfApelido) {
        this.mslfApelido = mslfApelido;
    }

    
    @Column(name="MSLF_email", nullable=false, length=100)
    public String getMslfEmail() {
        return this.mslfEmail;
    }
    
    public void setMslfEmail(String mslfEmail) {
        this.mslfEmail = mslfEmail;
    }

    
    @Column(name="MSLF_cpf", nullable=false, length=30)
    public String getMslfCpf() {
        return this.mslfCpf;
    }
    
    public void setMslfCpf(String mslfCpf) {
        this.mslfCpf = mslfCpf;
    }

    
    @Column(name="MSLF_rg", nullable=false, length=30)
    public String getMslfRg() {
        return this.mslfRg;
    }
    
    public void setMslfRg(String mslfRg) {
        this.mslfRg = mslfRg;
    }

    
    @Column(name="MSLF_sexo", nullable=false, length=10)
    public String getMslfSexo() {
        return this.mslfSexo;
    }
    
    public void setMslfSexo(String mslfSexo) {
        this.mslfSexo = mslfSexo;
    }

    
    @Column(name="MSLF_telefone", nullable=false, length=45)
    public String getMslfTelefone() {
        return this.mslfTelefone;
    }
    
    public void setMslfTelefone(String mslfTelefone) {
        this.mslfTelefone = mslfTelefone;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="MSLF_senha", nullable=false, length=10)
    public Date getMslfSenha() {
        return this.mslfSenha;
    }
    
    public void setMslfSenha(Date mslfSenha) {
        this.mslfSenha = mslfSenha;
    }

    
    @Column(name="MSLF_cep", nullable=false, length=45)
    public String getMslfCep() {
        return this.mslfCep;
    }
    
    public void setMslfCep(String mslfCep) {
        this.mslfCep = mslfCep;
    }

    
    @Column(name="MSLF_endereco", nullable=false, length=100)
    public String getMslfEndereco() {
        return this.mslfEndereco;
    }
    
    public void setMslfEndereco(String mslfEndereco) {
        this.mslfEndereco = mslfEndereco;
    }

    
    @Column(name="MSLF_bairro", nullable=false, length=50)
    public String getMslfBairro() {
        return this.mslfBairro;
    }
    
    public void setMslfBairro(String mslfBairro) {
        this.mslfBairro = mslfBairro;
    }

    
    @Column(name="MSLF_cidade", nullable=false, length=50)
    public String getMslfCidade() {
        return this.mslfCidade;
    }
    
    public void setMslfCidade(String mslfCidade) {
        this.mslfCidade = mslfCidade;
    }

    
    @Column(name="MSLF_estado", nullable=false, length=45)
    public String getMslfEstado() {
        return this.mslfEstado;
    }
    
    public void setMslfEstado(String mslfEstado) {
        this.mslfEstado = mslfEstado;
    }




}


