package bean;
// Generated 20/10/2023 13:43:36 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * MslfEntregas generated by hbm2java
 */
@Entity
@Table(name="MslfEntregas"
    ,catalog="db_mateus_fonseca"
)
public class MslfEntregas  implements java.io.Serializable {


     private int mslfIdEntregas;
     private MslfCliente mslfCliente;
     private MslfVendedor mslfVendedor;
     private String mslfCpf;
     private int mslfRg;
     private String mslfTelefone;
     private int mslfCep;
     private String mslfEndereco;
     private String mslfBairro;
     private String mslfCidade;
     private String mslfEstado;
     private int mslfNumeroCasa;
     private Date mslfData;

    public MslfEntregas() {
    }

    public MslfEntregas(int mslfIdEntregas, MslfCliente mslfCliente, MslfVendedor mslfVendedor, String mslfCpf, int mslfRg, String mslfTelefone, int mslfCep, String mslfEndereco, String mslfBairro, String mslfCidade, String mslfEstado, int mslfNumeroCasa, Date mslfData) {
       this.mslfIdEntregas = mslfIdEntregas;
       this.mslfCliente = mslfCliente;
       this.mslfVendedor = mslfVendedor;
       this.mslfCpf = mslfCpf;
       this.mslfRg = mslfRg;
       this.mslfTelefone = mslfTelefone;
       this.mslfCep = mslfCep;
       this.mslfEndereco = mslfEndereco;
       this.mslfBairro = mslfBairro;
       this.mslfCidade = mslfCidade;
       this.mslfEstado = mslfEstado;
       this.mslfNumeroCasa = mslfNumeroCasa;
       this.mslfData = mslfData;
    }
   
     @Id 

    
    @Column(name="MSLF_idEntregas", unique=true, nullable=false)
    public int getMslfIdEntregas() {
        return this.mslfIdEntregas;
    }
    
    public void setMslfIdEntregas(int mslfIdEntregas) {
        this.mslfIdEntregas = mslfIdEntregas;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="MSLF_idCliente", nullable=false)
    public MslfCliente getMslfCliente() {
        return this.mslfCliente;
    }
    
    public void setMslfCliente(MslfCliente mslfCliente) {
        this.mslfCliente = mslfCliente;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="MSLF_idVendedor", nullable=false)
    public MslfVendedor getMslfVendedor() {
        return this.mslfVendedor;
    }
    
    public void setMslfVendedor(MslfVendedor mslfVendedor) {
        this.mslfVendedor = mslfVendedor;
    }

    
    @Column(name="MSLF_cpf", nullable=false, length=30)
    public String getMslfCpf() {
        return this.mslfCpf;
    }
    
    public void setMslfCpf(String mslfCpf) {
        this.mslfCpf = mslfCpf;
    }

    
    @Column(name="MSLF_rg", nullable=false, length=30)
    public int getMslfRg() {
        return this.mslfRg;
    }
    
    public void setMslfRg(int mslfRg) {
        this.mslfRg = mslfRg;
    }

    
    @Column(name="MSLF_telefone", nullable=false, length=45)
    public String getMslfTelefone() {
        return this.mslfTelefone;
    }
    
    public void setMslfTelefone(String mslfTelefone) {
        this.mslfTelefone = mslfTelefone;
    }

    
    @Column(name="MSLF_cep", nullable=false, length=45)
    public int getMslfCep() {
        return this.mslfCep;
    }
    
    public void setMslfCep(int mslfCep) {
        this.mslfCep = mslfCep;
    }

    
    @Column(name="MSLF_endereco", nullable=false, length=100)
    public String getMslfEndereco() {
        return this.mslfEndereco;
    }
    
    public void setMslfEndereco(String mslfEndereco) {
        this.mslfEndereco = mslfEndereco;
    }

    
    @Column(name="MSLF_bairro", nullable=false, length=50)
    public String getMslfBairro() {
        return this.mslfBairro;
    }
    
    public void setMslfBairro(String mslfBairro) {
        this.mslfBairro = mslfBairro;
    }

    
    @Column(name="MSLF_cidade", nullable=false, length=50)
    public String getMslfCidade() {
        return this.mslfCidade;
    }
    
    public void setMslfCidade(String mslfCidade) {
        this.mslfCidade = mslfCidade;
    }

    
    @Column(name="MSLF_estado", nullable=false, length=45)
    public String getMslfEstado() {
        return this.mslfEstado;
    }
    
    public void setMslfEstado(String mslfEstado) {
        this.mslfEstado = mslfEstado;
    }

    
    @Column(name="MSLF_numero_casa", nullable=false)
    public int getMslfNumeroCasa() {
        return this.mslfNumeroCasa;
    }
    
    public void setMslfNumeroCasa(int mslfNumeroCasa) {
        this.mslfNumeroCasa = mslfNumeroCasa;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="MSLF_data", nullable=false, length=10)
    public Date getMslfData() {
        return this.mslfData;
    }
    
    public void setMslfData(Date mslfData) {
        this.mslfData = mslfData;
    }




}


